# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_jp', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('status', models.CharField(max_length=7)),
                ('first_appearance', models.IntegerField()),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('character_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_jp', models.CharField(blank=True, max_length=200)),
                ('org_type', models.CharField(max_length=200)),
                ('active', models.CharField(max_length=7)),
                ('first_appearance', models.IntegerField()),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('first_appearance', models.IntegerField()),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='base',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Place'),
        ),
        migrations.AddField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Character'),
        ),
        migrations.AddField(
            model_name='membership',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
    ]
