# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160523_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('N', 'Genderless')], default='U', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('L', 'Alive'), ('D', 'Deceased'), ('S', 'Cait Sith'), ('U', 'Unknown')], default='L', max_length=9),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('U', 'Unknown')], default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='organization',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Place'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Character'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
