# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_organization_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Character'),
        ),
    ]
